Added responsive fonts
NUS-Fintech-Society/SD_Fintech_Website pull request #69
Opened 2021-09-24 11:41 UTC by Zxun2

Changed the unit of measurement to rem (for fonts), and added some mixins for responsiveness. Let me know if anything else needs to be changed :)

Issue here: [https://github.com/NUS-Fintech-Society/SD_Fintech_Website/issues/57](url)

2021-09-25 06:02 UTC, jerrenss requested changes
Nice work! Just that the Event page's fonts look a little off hmm, you might wanna check out why. The regular body texts are too large and the headers are too small.

![image](https://user-images.githubusercontent.com/50544486/134760442-41bf9c91-af42-412b-858f-3231ef6b63f0.png)

2021-09-25 06:02 UTC, jerrenss commented on styles/variables.scss
> +$font-size-0: 1.8rem;
I see you added 8px to each of the originals, now it looks slightly big haha. Shall we follow this guideline instead? Feel free to change it up a little if you think the sizes are strange.

![image](https://user-images.githubusercontent.com/50544486/134760377-2fbfea93-2222-44a9-8cc6-352efc3c75dc.png)

Source: https://w3-lab.com/website-font-size-guidelines/

2021-09-30 09:12 UTC, Zxun2 commented
> Nice work! Just that the Event page's fonts look a little off hmm, you might wanna check out why. The regular body texts are too large and the headers are too small.
> 
> ![image](https://user-images.githubusercontent.com/50544486/134760442-41bf9c91-af42-412b-858f-3231ef6b63f0.png)

Fixed the weird sizing on the events page. Hopefully, things work out now! 

Issue here: [https://github.com/NUS-Fintech-Society/SD_Fintech_Website/issues/57](url)

2021-10-01 04:34 UTC, jerrenss commented
@Zxun2 could you help to resolve the merge conflicts? Update your master branch locally, and merge it into your working branch. Then manually resolve the conflicts ya

2021-10-01 05:44 UTC, Zxun2 commented
> @Zxun2 could you help to resolve the merge conflicts? Update your master branch locally, and merge it into your working branch. Then manually resolve the conflicts ya

Done! 

Issue here: [https://github.com/NUS-Fintech-Society/SD_Fintech_Website/issues/57](url)

2021-10-02 08:17 UTC, jerrenss commented
Hey @Zxun2 sflr, didn't see the notification. Could you help to check why there's this gap in the footer? Zhikai made a fix so there shouldn't be the contact form anymore in the production version

![image](https://user-images.githubusercontent.com/50544486/135709019-f591153f-a3c8-4c99-ba56-d89880edd794.png)

2021-10-02 09:01 UTC, Zxun2 commented
> Hey @Zxun2 sflr, didn't see the notification. Could you help to check why there's this gap in the footer? Zhikai made a fix so there shouldn't be the contact form anymore in the production version
> 
> ![image](https://user-images.githubusercontent.com/50544486/135709019-f591153f-a3c8-4c99-ba56-d89880edd794.png)
> 
> Also, could you can make the sub-draweritems smaller than the draweritems? ![image](https://user-images.githubusercontent.com/50544486/135709111-d4f2da0f-71e8-46cb-a1f0-073b744fb7ac.png)
> 
> Other than that, looks good :)

Done! Forgot to add changes previously haha. Also, did the tweak to the font size on the side drawer.   

Issue here: https://github.com/NUS-Fintech-Society/SD_Fintech_Website/issues/57

2021-10-02 16:01 UTC, jerrenss approved these changes

2021-10-02 16:01 UTC, merged