Add statistics section
NUS-Fintech-Society/SD_Fintech_Website pull request #70
Opened 2021-09-24 11:54 UTC by jianoway

2021-09-25 05:44 UTC, jerrenss requested changes
Other than that all's good, nice work!!

2021-09-25 05:44 UTC, jerrenss commented on pages/index.js
> +      const response = await request.get("events/")
For now, let's not use API calls as we are going to temporarily decouple the backend. All API calls have been removed in the latest master. It's fine to use constant values for the stats.

2021-09-25 05:44 UTC, jerrenss commented on pages/index.js
> +          <script>
Shall we have the statistics displayed near the top of the screen, below About Us? Feel free to use these for inspiration:

![image](https://user-images.githubusercontent.com/50544486/134760003-9f9d2c72-bb6e-4787-ab1d-af6530075f35.png)

![image](https://user-images.githubusercontent.com/50544486/134760009-82ee915a-4989-4539-98d8-3f40baabb7a9.png)

2021-09-25 06:42 UTC, jianoway commented
I added the statistics section to below the About Us section. The background image used is from [here](https://unsplash.com/photos/17_tB-oI0ao) and is licensed to be used for commercial and non-commercial purposes for free. The image is just placeholder and can be changed to a more appropriate one. Please let me know how this iteration looks, thanks!

2021-09-25 07:06 UTC, jerrenss commented
It looks much better! Since we are going to deploy this, let's not use the placeholder image as it dosen't fit the overall look. Let's go for a more minimalist design first? Something like this.

![image](https://user-images.githubusercontent.com/50544486/134762195-6dedf08f-ae33-40a8-88f0-759d6616f175.png)

Changes:
- Remove fixed width
- Add border radius of 8px
- Change fonts to black
- Use background-color #F5F5F5 instead of background-image
- Remove <h1/> header

As an optional added challenge, try to make this mobile responsive. Such that when the user views it on his phone, it still looks decent. Can use Chrome Dev Tools or manually shrink the browser to test this

2021-09-25 11:26 UTC, jianoway commented
Thanks for the CountUp suggestion, wasn't aware of the existence of the library until now!

2021-09-25 15:07 UTC, jerrenss commented
Great work!! Am trying to get the actual stats from the exco. Will approve and merge once the numbers are confirmed :)

2021-09-29 10:41 UTC, jerrenss approved these changes

2021-09-29 10:41 UTC, merged